name: image-reading2 # you probably want to 'snapcraft register <name>'
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: My 1st snap ever # 79 char long summary
description: |
  This is my-snaps description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  image-reading2:
    command: image-reading2
  
parts:
  
  files-copy:
    plugin: copy
    source: ./src
    files: 
        /usr/local/lib/libopencv_core.so.3.2.0 : libopencv_core.so.3.2.0
        /usr/local/lib/libopencv_highgui.so.3.2.0 : libopen_highgui.so
        /usr/local/lib/libopencv_imgproc.so.3.2.0 : libopencv_imgproc.so
        /usr/local/lib/libopencv_imgcodecs.so.3.2.0 : libopencv_imgcodecs.so
  
    stage:
        - libopencv_core.so
        - libopencv_highgui.so
        - libopencv_imgcodecs.so
        - libopencv_imgproc.so
  
  image-reading2:
    plugin: cmake
    source: ./src
    build-packages:
        - g++
    after: [files-copy]
